### ISSUE TITLE
[Code] Name is stored as event's topic

### ISSUE THREAD

**Issue by sebaraba** [iikirilov/web3j-workshop#2]
## To Do:
- [ ] Adjust the code in Application.java file such that the we can get the string from of the sender's name;

At the moment the name is an indexed parameter of the `MessageReceived`'s event. Thus the name is always stored as one of the three event's `topics`, which are of fixed length. The `name` variable will be stored as the hash of the value in the `topics` as strings have an arbitrary length. Unfortunately there is no reasonable way to decode a hashed value and the name would be impossible to recover. Future work proposes to solve this problem.

**Comment by iikirilov** [comment]
Thanks for describing this issue. May I note that the code in `Application` is fine. The issue is in fact that the `name` parameter is `indexed`, which is why it is stored in the `topics` of the transaction log. Therefore it is the contract that needs to be modified/recompiled/smart contract wrapper regenerated.

I propose that the `indexed` modifier is removed for the `name` parameter in the event signature. This would mean that the `data` field in the transaction log would hold both the `message` and the `name`.

 I believe Web3j will decode the data field automagically into the `message` and `name` variables.

**Comment by iikirilov** [comment]
Fixed.
